### PR TITLE
Token generation

### PR DESCRIPTION
**Pull request by apolloLegends**
I came across a problem then trying to generate a token from a 10.2.2 server.  This is a private server and they would not be happy for me to provide the end point nor credentials. 

This is the error message that was returned from the server when generating the token:

**Exception in generating tokenFailed to generate a token for the user.Client ID is required for long expiration tokens**

The solution to the problem was to set the referrer property of the TokenProvider class. However, I wasn't able to figure out a way how to do this without modifying the gateway constructor (and it seemed to make sense as that's where we are also providing username and password parameters).  Everything else was hooked correctly otherwise.

I see this as a patch to the master and have submitted it thusly.

### CODE REVIEW

**Comment by davetimmins** [comment]
Hi,

you can do this already by creating the token provider first then passing it to the portal gateway. Also, the referer doesn't mean anything to the partal gateway, only the token provider. So I won't be merging this PR, thanks anyway though.

**Comment by apolloLegends** [comment]
The logic contained within the PortGateway.Create function handles the detection of which TokenProvider that needs to be created for the specific server.  Am I right to understand that I need to essentially duplicate this code by

- creating a gateway to get the server information 
- perform the same checks as in the static Create methods to determine which token provider I need
- create the token provider
- create another gateway to set the referrer information to query the server?

If so it would seem that moving that code to a static function on TokenProvider class may make sense.

**Comment by davetimmins** [comment]
That function is for when you don't know (or care) about the specific URIs used but want to have the code discover the correct endpoints. Sounds more like in your circumstance that you already know where the correct endpoints are so you can skip straight to creating the token provider and gateway, there are some examples of this in the test project https://github.com/davetimmins/Anywhere.ArcGIS/blob/d8900f0a430c0c420b3a6606d82e152796acea2c/tests/Anywhere.ArcGIS.Test.Integration/SecureGISGatewayTests.cs#L133

**Comment by apolloLegends** [comment]
Thanks for the assistance.

**Pull request closed without merging**
