### PR TITLE
Changed MinimumScale and Maximum Scale to double?

### PR DESCRIPTION
**Pull request by mgayheart1**
#46 
Changed int to double? for both parameters. Added a test service to CanDescribeLayer that has a double MinScale. It will fail on older builds and pass with the change to double.

### CODE REVIEW

**Comment by mgayheart1** [comment]
The build script completed on my system. I didn't check in a csproj file, so not sure why the CI build is failing. What needs to be changed?

**Comment by mgayheart1** [comment]
I copied in the original set of urls to test against after running build.bat. I missed that copying it in messed up the double quotes character.

**Comment by davetimmins** [comment]
Thanks, I'm traveling at the moment so may not do a release until next week but the myget feed should have the change in it.

**Comment by mgayheart1** [comment]
I have a production deploy this week that could take advantage of this fix. Could a build be available this week? Thanks so much!

**Pull request merged**
